### ISSUE TITLE
Not working, when application is killed.

### ISSUE THREAD

**Issue by Aaqib925** [Mobeye/react-native-mobeye-geolocation#14]
Is there any way to get location updates even when the application is killed?

**Comment by MorvanL** [comment]
Unfortunately, I don't think so. I think that if the application is killed it can't perform any action

**Comment by MorvanL** [comment]
Unfortunately, I don't think so. If the application is killed it can't perform any action

**Comment by MorvanL** [comment]
Maybe you can try with a service or something similar that will run even if the application is killed

**Comment by PABourdais** [comment]
It might be possible using a sticky service, look at this for android : [article](https://medium.com/@ross_12208/android-location-tracking-foreground-background-force-killed-app-accuracy-aspects-24a151629f22) 

We will not work on this feature because we don't need it in our app.

Be carefull about android policy on background location : [limits](https://developer.android.com/about/versions/oreo/background)
