### ISSUE TITLE
on background mode issue 

### ISSUE THREAD

**Issue by amiradgham** [Mobeye/react-native-mobeye-geolocation#48]
the value of geo location is always the same value while the app is on background mode .

**Comment by MorvanL** [comment]
Yes, maybe we should be more clear about the background in the readme. We don't use background localization internally and we don't have time to upgrade the library to handle background properly. So it probably doesn't work well for background.
Nevertheless, I think that the library still allows to get position in background. On android I know that it can be a question of permissions, because the last versions of android ask for particular permissions for background use. For ios I don't have more info to give you, sorry.

**Comment by MorvanL** [comment]
https://github.com/Mobeye/react-native-mobeye-geolocation/commit/d7ffd5453dead74565a15982a2f0521713eb2299
